import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Link from "next/link";
import Image from "next/image";
import { SignedIn, UserButton } from "@clerk/nextjs";
import {dark} from "@clerk/themes";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="bg-black">
          <div className="w-full min-h-screen flex flex-col lg:flex-row">
            <div className="w-full lg:w-1/6 border-slate-800 lg:border-r lg:block hidden">
              <div className="p-3">
                <Link href={"/"}>Home</Link>
              </div>
              <div className="p-3">
                <SignedIn>
                  <UserButton />
                </SignedIn>
              </div>
            </div>
            <div className="w-full lg:w-2/3 border-slate-800 lg:border-r">{children}</div>
            <div className="w-full lg:w-1/6">
              <div className="p-3">
                <Link href={"/similar"}>Find someone</Link>
              </div>
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
